class ClubList
  LIST = [
      "Adelaide United",
      "Newcastle Jets",
      "Brisbane Roar",
      "Perth Glory",
      "Central Coast",
      "Sydney FC",
      "Melb. Victory",
      "Well. Phoenix",
      "Melbourne City",
      "WS Wanderers",
      "Busan I'Park",
      "Jeonnam Dragons",
      "FC Seoul",
      "Pohang Steelers",
      "GyeongNam FC",
      "Sangju Sangmu",
      "Incheon United",
      "Seongnam FC",
      "Jeju United FC",
      "Suwon Bluewings",
      "Jeonbuk FC",
      "Ulsan Hyundai",
      "Al-Ahli",
      "Al-Orubah FC",
      "Al-Faisaly",
      "Al-Raed",
      "Al-Fateh",
      "Al-Shabab",
      "Al-Hilal",
      "Alshoulla",
      "Al-Ittihad",
      "Al-Taawoun",
      "Al-Khaleej",
      "Hajer",
      "Al-Nassr",
      "Najran",
      "Admira",
      "SK Sturm Graz",
      "FK Austria",
      "SV Grödig",
      "RB Salzburg",
      "SV Ried",
      "SCR Altach",
      "Wiener Neustadt",
      "SK Rapid Wien",
      "Wolfsberger AC",
      "Cercle Brugge",
      "Lierse SK",
      "Club Brugge",
      "Royal Mouscron",
      "KAA Gent",
      "RSC Anderlecht",
      "KRC Genk",
      "Sp. Charleroi",
      "KV Kortrijk",
      "Sport. Lokeren",
      "KV Mechelen",
      "Standard Liège",
      "KV Oostende",
      "Waasl.-Beveren",
      "KVC Westerlo",
      "Zulte-Waregem",
      "Aalborg BK",
      "FC Vestsjælland",
      "Brøndby IF",
      "Hobro IK",
      "Esbjerg fB",
      "Odense Boldklub",
      "FC København",
      "Randers FC",
      "FC Midtjylland",
      "Silkeborg IF",
      "FC Nordsjælland",
      "SønderjyskE",
      "Arsenal",
      "Manchester Utd",
      "Aston Villa",
      "Newcastle Utd",
      "Burnley",
      "QPR",
      "Chelsea",
      "Southampton",
      "Crystal Palace",
      "Spurs",
      "Everton",
      "Stoke City",
      "Hull City",
      "Sunderland",
      "Leicester City",
      "Swansea City",
      "Liverpool",
      "West Brom",
      "Manchester City",
      "West Ham",
      "Birmingham City",
      "Ipswich Town",
      "Blackburn Rvrs",
      "Leeds United",
      "Blackpool",
      "Middlesbrough",
      "Bolton",
      "Millwall",
      "Bournemouth",
      "Norwich City",
      "Brentford",
      "Nott'm Forest",
      "Brighton",
      "Reading",
      "Cardiff City",
      "Rotherham Utd",
      "Charlton Ath",
      "Sheffield Wed",
      "Derby County",
      "Watford",
      "Fulham",
      "Wigan Athletic",
      "Huddersfield",
      "Wolves",
      "Barnsley",
      "MK Dons",
      "Bradford City",
      "Notts County",
      "Bristol City",
      "Oldham Athletic",
      "Chesterfield",
      "Peterborough",
      "Colchester",
      "Port Vale",
      "Coventry City",
      "Preston",
      "Crawley Town",
      "Rochdale",
      "Crewe Alexandra",
      "Scunthorpe Utd",
      "Doncaster",
      "Sheffield Utd",
      "Fleetwood Town",
      "Swindon Town",
      "Gillingham",
      "Walsall",
      "Leyton Orient",
      "Yeovil Town",
      "Accrington",
      "Morecambe",
      "AFC Wimbledon",
      "Newport County",
      "Burton Albion",
      "Northampton",
      "Bury",
      "Oxford United",
      "Cambridge Utd",
      "Plymouth Argyle",
      "Carlisle United",
      "Portsmouth",
      "Cheltenham Town",
      "Shrewsbury",
      "Dagenham",
      "Southend United",
      "Exeter City",
      "Stevenage",
      "Hartlepool",
      "Tranmere Rovers",
      "Luton Town",
      "Wycombe",
      "Mansfield Town",
      "York City",
      "AS Monaco",
      "OGC Nice",
      "Bordeaux",
      "Olympique Lyon",
      "EA Guingamp",
      "PSG",
      "Evian Thonon FC",
      "RC Lens",
      "FC Lorient",
      "Saint-Etienne",
      "FC Metz",
      "SC Bastia",
      "FC Nantes",
      "SM Caen",
      "LOSC Lille",
      "Stade Reims",
      "Marseille",
      "Stade Rennais",
      "Montpellier HSC",
      "Toulouse FC",
      "AC Ajaccio",
      "GFC Ajaccio",
      "AC Arles",
      "Le Havre AC",
      "AJ Auxerre",
      "LB Chateauroux",
      "Angers SCO",
      "Nîmes Olympique",
      "AS Nancy",
      "Stade Brest",
      "Cham. Niortais",
      "Stade Lavallois",
      "Clermont Foot",
      "Tours FC",
      "Dijon FCO",
      "US Créteil",
      "ES Troyes",
      "US Orléans",
      "FC Sochaux",
      "Valenciennes FC",
      "1. FC Köln",
      "FC Schalke 04",
      "1. FSV Mainz 05",
      "Hamburger SV",
      "1899 Hoffenheim",
      "Hannover 96",
      "Bayer 04",
      "Hertha BSC",
      "Bor. Dortmund",
      "SC Freiburg",
      "Bor. M'gladbach",
      "SC Paderborn",
      "Eint. Frankfurt",
      "VfB Stuttgart",
      "FC Augsburg",
      "VfL Wolfsburg",
      "FC Bayern",
      "Werder Bremen",
      "1. FC K'lautern",
      "FSV Frankfurt",
      "1. FC Nuremberg",
      "Greuther Fürth",
      "1860 Munich",
      "Heidenheim",
      "Braunschweig",
      "Karlsruher SC",
      "Darmstadt",
      "RB Leipzig",
      "Erzgebirge Aue",
      "SV Sandhausen",
      "F. Düsseldorf",
      "Union Berlin",
      "FC Ingolstadt",
      "VfL Bochum",
      "FC St. Pauli",
      "VfR Aalen",
      "Atalanta",
      "Lazio",
      "Cagliari",
      "Milan",
      "Cesena",
      "Napoli",
      "Chievo Verona",
      "Palermo",
      "Empoli",
      "Parma",
      "Fiorentina",
      "Roma",
      "Genoa",
      "Sampdoria",
      "Hellas Verona",
      "Sassuolo",
      "Inter",
      "Torino",
      "Juventus",
      "Udinese",
      "Avellino",
      "Lanciano",
      "Bari",
      "Latina",
      "Bologna",
      "Livorno",
      "Brescia",
      "Modena",
      "Carpi",
      "Perugia",
      "Catania",
      "Pescara",
      "Chiavari",
      "Terni",
      "Cittadella",
      "Trapani",
      "Crotone",
      "Varese",
      "Frosinone",
      "Vercelli",
      "La Spezia",
      "Borgocalcio",
      "ADO Den Haag",
      "Go Ahead Eagles",
      "Ajax",
      "Heracles Almelo",
      "AZ",
      "NAC Breda",
      "Excelsior",
      "PEC Zwolle",
      "FC Dordrecht",
      "PSV",
      "FC Groningen",
      "SC Cambuur",
      "FC Twente",
      "sc Heerenveen",
      "FC Utrecht",
      "Vitesse",
      "Feyenoord",
      "Willem II",
      "Aalesunds FK",
      "Sarpsborg",
      "FK Bodø/Glimt",
      "SK Brann",
      "FK Haugesund",
      "Sogndal",
      "Lillestrøm SK",
      "Stabæk Fotball",
      "Molde FK",
      "Start",
      "ODD",
      "Strømsgodset IF",
      "Rosenborg BK",
      "Vålerenga",
      "Sandnes Ulf",
      "Viking FK",
      "Cracovia",
      "Legia Warszawa",
      "GKS Bełchatów",
      "Piast Gliwice",
      "Górnik Łęczna",
      "Podbeskidzie",
      "Górnik Zabrze",
      "Pogoń Szczecin",
      "Jagiellonia",
      "Ruch Chorzów",
      "Korona Kielce",
      "Śląsk Wrocław",
      "Lech Poznań",
      "Wisła Kraków",
      "Lechia Gdańsk",
      "Zawisza",
      "Académica",
      "Moreirense FC",
      "Belenenses",
      "Paços Ferreira",
      "Boavista",
      "Penafiel",
      "CD Nacional",
      "Rio Ave FC",
      "CS Marítimo",
      "SC Braga",
      "Estoril-Praia",
      "SL Benfica",
      "FC Arouca",
      "Sporting CP",
      "FC Porto",
      "Vit. Guimarães",
      "Gil Vicente",
      "Vitória FC",
      "Athlone Town",
      "Dundalk",
      "Bohemians FC",
      "Limerick",
      "Bray Wanderers",
      "Shamrock Rovers",
      "Cork City",
      "Sligo Rovers",
      "Derry City",
      "St. Pats",
      "Drogheda Utd",
      "UCD AFC",
      "Amkar Perm",
      "Kuban Krasnodar",
      "Arsenal Tula",
      "Lokomotiv",
      "CSKA Moskva",
      "Mordovia Saransk",
      "Dinamo Moskva",
      "Rubin Kazan",
      "FC Krasnodar",
      "Spartak Moskva",
      "FC Rostov",
      "Terek Grozny",
      "FC Ufa",
      "Torpedo Moskva",
      "FC Ural",
      "Zenit",
      "Aberdeen",
      "Kilmarnock",
      "Celtic",
      "Motherwell",
      "Dundee FC",
      "Partick Thistle",
      "Dundee United",
      "Ross County",
      "Hamilton",
      "St. Johnstone",
      "Inverness CT",
      "St. Mirren",
      "Athletic Bilbao",
      "Rayo Vallecano",
      "Atlético Madrid",
      "RC Deportivo",
      "Celta Vigo",
      "RCD Espanyol",
      "Córdoba CF",
      "Real Madrid",
      "Elche CF",
      "Real Sociedad",
      "FC Barcelona",
      "SD Eibar",
      "Getafe CF",
      "Sevilla FC",
      "Granada CF",
      "UD Almería",
      "Levante UD",
      "Valencia CF",
      "Málaga CF",
      "Villarreal CF",
      "AD Alcorcón",
      "RC Recreativo",
      "Albacete",
      "RCD Mallorca",
      "CA Osasuna",
      "Real Betis",
      "CD Leganés",
      "CD Mirandes",
      "CD Lugo",
      "Real Valladolid",
      "CD Numancia",
      "Real Zaragoza",
      "CD Tenerife",
      "Sabadell FC",
      "Deport. Alavés",
      "SD Ponferradina",
      "FC Barcelona B",
      "Sporting Gijón",
      "Girona CF",
      "UD Las Palmas",
      "Racing Santander",
      "UE Llagostera",
      "AIK Fotboll",
      "Helsingborgs IF",
      "Åtvidabergs FF ",
      "IF Elfsborg",
      "BK Häcken",
      "IFK Göteborg",
      "Brommapojkarna",
      "IFK Norrköping",
      "Djurgårdens IF",
      "Kalmar FF",
      "Falkenbergs FF",
      "Malmö FF",
      "Gefle IF",
      "Mjällby AIF ",
      "Halmstads BK",
      "Örebro SK",
      "BSC Young Boys",
      "FC St. Gallen",
      "FC Aarau",
      "FC Thun",
      "FC Basel",
      "FC Vaduz",
      "FC Luzern",
      "FC Zürich",
      "FC Sion",
      "Grasshopper",
      "Akhisarspor",
      "Galatasaray SK",
      "Balıkesirspor",
      "Gaziantepspor",
      "Başakşehir",
      "Gençlerbirliği",
      "Beşiktaş JK",
      "Karabükspor",
      "Bursaspor",
      "Kasimpaşa SK",
      "Çaykur Rizespor",
      "Konyaspor",
      "Erciyesspor",
      "Mersin",
      "Eskişehirspor",
      "Sivasspor",
      "Fenerbahçe SK",
      "Trabzonspor",
      "América",
      "Pachuca",
      "Atlas",
      "Puebla",
      "Chiapas",
      "Querétaro",
      "Club León",
      "Santos Laguna",
      "Cruz Azul",
      "Tigres",
      "Guadalajara",
      "Tijuana",
      "Leones Negros",
      "Toluca",
      "Monarcas",
      "U.N.A.M.",
      "Monterrey",
      "Veracruz",
      "Chicago Fire",
      "NY Red Bulls",
      "Chivas USA",
      "Philadelphia",
      "Colorado Rapids",
      "Portland",
      "Columbus Crew",
      "Real Salt Lake",
      "D.C. United",
      "SJ Earthquakes",
      "FC Dallas",
      "Sounders FC",
      "Houston Dynamo",
      "Sporting KC",
      "LA Galaxy",
      "Toronto FC",
      "Montreal Impact",
      "Whitecaps FC",
      "New England",
      "Bahía Blanca",
      "Newell's",
      "Banfield",
      "Quilmes",
      "Belgrano",
      "Racing Club",
      "Boca Juniors",
      "Rafaela",
      "Estudiantes",
      "River Plate",
      "Fl. Varela",
      "Rosario Ctral. ",
      "G. La Plata",
      "San Lorenzo",
      "Godoy Cruz",
      "Sarandí",
      "Independiente",
      "Tigre",
      "Lanús",
      "Vélez Sarsfield",
      "AC Barnechea",
      "Depor. Iquique",
      "Audax Italiano",
      "Ñublense",
      "CD Antofagasta",
      "San Marcos",
      "CD Cobreloa",
      "Uni. Católica",
      "CD Cobresal",
      "Uni. Concepción",
      "CD Huachipato",
      "Uni. de Chile",
      "CD O'Higgins",
      "Unión Española",
      "CD Palestino",
      "Unión La Calera",
      "Colo-Colo",
      "Wanderers",
      "Águilas Doradas",
      "Fortaleza FC",
      "Al. Petrolera",
      "Ind. Santa Fe",
      "Atl. Nacional",
      "Indep. Medellín",
      "Atlético Huila",
      "Junior FC",
      "Boyacá Chicó",
      "La Equidad",
      "Deportes Tolima",
      "Millonarios FC",
      "Deportivo Cali",
      "Once Caldas",
      "Deportivo Pasto",
      "Patriotas FC",
      "Envigado",
      "Uniautónoma FC",
      "adidas All-Star",
      "Orlando Pirates",
      "Classic XI",
      "Panathinaikos",
      "FC Shakhtar",
      "PAOK",
      "Kaizer Chiefs",
      "Rangers",
      "MLS All Stars",
      "World XI",
      "Olympiakos CFP",
      "Argentina",
      "Korea Republic",
      "Australia",
      "Mexico",
      "Austria",
      "Netherlands",
      "Belgium",
      "New Zealand",
      "Bolivia",
      "Northern Ireland",
      "Brazil",
      "Norway",
      "Bulgaria",
      "Paraguay",
      "Cameroon",
      "Peru",
      "Chile",
      "Poland",
      "Colombia",
      "Portugal",
      "Côte d'Ivoire",
      "Romania",
      "Czech Republic",
      "Russia",
      "Denmark",
      "Scotland",
      "Ecuador",
      "Slovenia",
      "Egypt",
      "South Africa",
      "England",
      "Spain",
      "Finland",
      "Sweden",
      "France",
      "Switzerland",
      "Germany",
      "Turkey",
      "Greece",
      "United States",
      "Hungary",
      "Uruguay",
      "India",
      "Venezuela",
      "Ireland",
      "Wales",
      "Italy"
  ]
end